name: med_net
description: A modern healthcare Flutter application
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  fl_chart: ^0.70.0

  # Networking & Storage
  http: ^1.2.1
  shared_preferences: ^2.3.2

  # Media & Sensors
  image_picker: ^1.1.2
  health: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
